### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by josephgupkim** [gflujan/jammming-app#2]
Upon getting your project setup on my local machine, it seems that it's not functioning as intended.

- Cannot connect to Spotify.
- Unable to search songs.
- Unable to add/remove songs to playlist due the above reason.
- No console log errors show up.
- Please leave out your "node_modules" folder next time as it's unnecessary to include.

**Comment by gflujan** [comment]
Is this the extent of the review? If so, I have to say I'm greatly disappointed in the lack of any possible solutions or points to look at for resolutions.

I was aware of those issues when I submitted for review. I was hoping that I would receive some pointers on mistakes I made, how I could fix them, or ideas to pay attention to. Overall, I'd like some constructive criticism that actually teaches me. Just saying "it's broken" doesn't really help me.

Please let me know if you're able to provide something a little more tangible. Thanks!

**Comment by josephgupkim** [comment]
If you need points to look for and solutions, please utilize the Codecademy advisors you have through your Pro account. They are available to help you through these "tough times" and aid you in overcoming whatever issues may be occurring.

The projects submitted for project review should be in a functional state as they are graded and counted towards the requirements for the digital certificate.

If attempting to finish this project proves too difficult then I will more than gladly send you some solutions.

**Comment by gflujan** [comment]
Resolved. (Metal Gabe, 24-Feb-2021 @ 00:35) (2021_0223--updates)
